apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-RuoYi-Vue.yaml convert  
  labels:
    reuoyi.service: ruoyi-db
  name: ruoyi-db
spec:
  replicas: 1
  selector:
    matchLabels:
      reuoyi.service: ruoyi-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-RuoYi-Vue.yaml convert       
      labels:
        io.kompose.network/ruoyi-dev-network: "true"
        reuoyi.service: ruoyi-db
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123"
          image: registry.cn-hangzhou.aliyuncs.com/smartide/mysql:8.0.21
          name: ruoyi-db
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "1000m"

      restartPolicy: Always

status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-RuoYi-Vue.yaml convert  
  labels:
    reuoyi.service: ruoyi-db
  name: ruoyi-db
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    reuoyi.service: ruoyi-db
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-RuoYi-Vue.yaml convert  
  labels:
    reuoyi.service: ruoyi-dev
  name: ruoyi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      reuoyi.service: ruoyi-dev
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-RuoYi-Vue.yaml convert      
      labels:
        io.kompose.network/ruoyi-dev-network: "true"
        reuoyi.service: ruoyi-dev
    spec:
      containers:
        - env:
            - name: LOCAL_USER_PASSWORD
              value: root123
            - name: ROOT_PASSWORD
              value: root123
          image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-java-v2-vscode:openjdk-11-jdk
          name: ruoyi-dev
          ports:
            - containerPort: 8080
            - containerPort: 8000
            - containerPort: 6822
            - containerPort: 6800
          resources: {}

      restartPolicy: Always

status: {}

--- 

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:  
  name: ruoyi-dev-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/ruoyi-dev-network: "true"
  podSelector:
    matchLabels:
      io.kompose.network/ruoyi-dev-network: "true"

--- 

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-RuoYi-Vue.yaml convert
  labels:
    reuoyi.service: ruoyi-dev
  name: ruoyi-dev
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "6822"
      port: 6822
      targetPort: 22
    - name: "6800"
      port: 6800
      targetPort: 3000
  selector:
    reuoyi.service: ruoyi-dev
status:
  loadBalancer: {}

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-RuoYi-Vue.yaml convert
  labels:
    reuoyi.service: ruoyi-phpmyadmin
  name: ruoyi-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      reuoyi.service: ruoyi-phpmyadmin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-RuoYi-Vue.yaml convert
      labels:
        io.kompose.network/ruoyi-dev-network: "true"
        reuoyi.service: ruoyi-phpmyadmin
    spec:
      containers:
        - env:
            - name: PMA_ARBITRARY
              value: "1"
          image: registry.cn-hangzhou.aliyuncs.com/boathouse/phpmyadmin:5.0.4-apache
          name: ruoyi-phpmyadmin
          ports:
            - containerPort: 80
            - containerPort: 8090
          resources: {}
      restartPolicy: Always
status: {}

--- 

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-RuoYi-Vue.yaml convert
  labels:
    reuoyi.service: ruoyi-phpmyadmin
  name: ruoyi-phpmyadmin
spec:
  ports:
    - name: "8090"
      port: 8090
      targetPort: 80
  selector:
    reuoyi.service: ruoyi-phpmyadmin
status:
  loadBalancer: {}


---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-RuoYi-Vue.yaml convert
  labels:
    reuoyi.service: ruoyi-redis
  name: ruoyi-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      reuoyi.service: ruoyi-redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-RuoYi-Vue.yaml convert
      labels:
        io.kompose.network/ruoyi-dev-network: "true"
        reuoyi.service: ruoyi-redis
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/smartide/redis:6.0.6
          name: ruoyi-redis
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}


--- 

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-RuoYi-Vue.yaml convert
  labels:
    reuoyi.service: ruoyi-redis
  name: ruoyi-redis
spec:
  ports:
    - name: 6379-tcp
      port: 6379
      targetPort: 6379
  selector:
    reuoyi.service: ruoyi-redis
status:
  loadBalancer: {}