name: "ruoyi"
services:

  frontend:
    image: ruoyi-ui
    build:
      context: ./ruoyi-ui
      dockerfile: ../frontend.Dockerfile
    ports:
      - 80:80
    #volumes:
    #- ./ruoyi-ui/nginx-sample.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net-1
    healthcheck:
      test: [ "CMD", "curl","-f","http://localhost:80" ]
      interval: 5s
    depends_on:
      backend:
        condition: service_healthy

  backend:
    image: ruoyi-admin
    build:
      dockerfile: backend.Dockerfile
    command: [
      "--ruoyi.profile=/home/ruoyi/uploadPath",
      "--spring.datasource.druid.master.url=jdbc:mysql://mysql:3306/ry-vue?useUnicode=true&characterEncoding=utf8",
      "--spring.datasource.druid.master.username=root",
      "--spring.datasource.druid.master.password=123456",
      "--spring.redis.host=redis"
    ]
    ports:
      - 8080:8080
    volumes:
      - data-upload:/home/ruoyi/uploadPath
    networks:
      - net-1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ry-vue
    ports:
      - 3306:3306
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_general_ci",
      "--skip-character-set-client-handshake"
    ]
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - data-mysql:/var/lib/mysql
    networks:
      - net-1
    healthcheck:
      #test: [ "CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p123456' ]
      test: [ "CMD-SHELL", 'mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD || exit 1' ]
      interval: 5s
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:6.0
    ports:
      - 6379:6379
    volumes:
      - data-redis:/data
    networks:
      - net-1
    healthcheck:
      test: [ "CMD", 'redis-cli',"ping" ]
      interval: 5s

volumes:
  data-mysql:
  data-redis:
  data-upload:

networks:
  net-1: