server:
  port: 8181


spring:
  datasource:
    url: jdbc:mysql://3ig3294254.zicp.fun:42639/gyfortest?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: gongyu
    password: wtxf4949
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true




#mybatis-plus:
#  mapper-locations: classpath:mapper/**/**Mapper.xml

mybatisNoSpringMappersLocation: invest.lixinger.ruoyi.mapper