# 数据源配置
spring:
  datasource:
    dynamic:
      primary: master
      hikari:
        connection-timeout: 30000
        validation-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 30000
        max-pool-size: 30
        min-idle: 10
        initialization-fail-timeout: 30000
        connection-init-sql: select 1
        connection-test-query: select 1
        is-auto-commit: true
        is-read-only: false
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.16.30.243:6060/ruoyi?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: LOLm2dI2UQF#RxOf
        teemlink:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://172.16.30.233:1433;DatabaseName=obpm_LianCheng_Data
          username: sa
          password: Lcdatacenter_888
        compute:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://172.16.30.233:1433;DatabaseName=uv_compute
          username: sa
          password: Lcdatacenter_888
        clean:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://172.16.30.233:1433;DatabaseName=uv_clean
          username: sa
          password: Lcdatacenter_888

#        druid:
#            statViewServlet:
#                enabled: true
#                # 设置白名单，不填则允许所有访问
#                allow:
#                url-pattern: /druid/*
#                # 控制台管理用户名和密码
#                login-username:
#                login-password:
#        dynamic:
#            druid:
#                # 初始连接数
#                initialSize: 5
#                # 最小连接池数量
#                minIdle: 10
#                # 最大连接池数量
#                maxActive: 20
#                # 配置获取连接等待超时的时间
#                maxWait: 60000
#                # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#                timeBetweenEvictionRunsMillis: 60000
#                # 配置一个连接在池中最小生存的时间，单位是毫秒
#                minEvictableIdleTimeMillis: 300000
#                # 配置一个连接在池中最大生存的时间，单位是毫秒
#                maxEvictableIdleTimeMillis: 900000
#                # 配置检测连接是否有效
#                validationQuery: SELECT 1
#                testWhileIdle: true
#                testOnBorrow: false
#                testOnReturn: false
##                webStatFilter:
##                    enabled: true
##                filters: stat,wall
##                wall:
##                    multiStatementAllow: true
#                stat:
#                    log-slow-sql: true
#                    slow-sql-millis: 1000
#                    merge-sql: true
#            primary: master
#            datasource:
#                # 主库数据源
#                master:
#                    driver-class-name: com.mysql.jdbc.Driver
#                    url: jdbc:mysql://172.16.30.243:6060/ruoyi?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#                    username: root
#                    password: LOLm2dI2UQF#RxOf
#                # 从库数据源
##                slave:
##                    # 从数据源开关/默认关闭
##                    enabled: false
##                    url:
##                    username:
##                    password:
#                teemlink:
#                    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#                    url: jdbc:sqlserver://172.16.30.233:1433;DatabaseName=obpm_LianCheng_Data
#                    username: sa
#                    password: Lcdatacenter_888
#                compute:
#                    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#                    url: jdbc:sqlserver://172.16.30.233:1433;DatabaseName=uv_compute
#                    username: sa
#                    password: Lcdatacenter_888
#                clean:
#                    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#                    url: jdbc:sqlserver://172.16.30.233:1433;DatabaseName=uv_clean
#                    username: sa
#                    password: Lcdatacenter_888