# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: false
    livereload:
      enabled: false
  # redis 配置
  redis:
#    cluster:
#      nodes: 192.168.0.114:6379
#    password: Aa123456
    # 地址
    host: 192.168.0.114
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: Aa123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://192.168.0.141:3306/ut_blueprint?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: Dev
        password: uc66666
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: admin
        login-password: WQ0le1X4iD4TMbr6R98Lcv0oGJ8O5knq
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  data:
    mongodb:
      uri: mongodb://nsuser:YdRijOnbo#UxXVMgiLSaA@192.168.10.156:8635,192.168.10.155:8635/neighbour-resource?authSource=neighbour-resource&connect=replicaSet&readPreference=secondaryPreferred&safe=true&authMechanism=SCRAM-SHA-1

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: f8a8f0e0-9947-491c-8187-a3258d1e283f
  # 令牌有效期（默认30分钟）
  expireTime: 360

## ut-touch 接口配置
ut-touch:
  api-url: https://ut-openapi.csbilin.com
  merchant-account: bilin2
  merchant-password: bilin123
  touch-merchant-id: 1735130303135006720

openapi:
  openApiKey: yriWvNH7Bt83mCvTQYHMLkMbuh7Ll32z
  openApiSecret: TNRlS8MebxpBYvpbpWEwByzBAhw5TAfg
  openApiHost: https://gateway.test.csbilin.com

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /


bot:
  api-url: https://30q623450x.vicp.fun