# 项目相关配置
ruoyi:
  # 名称
  name: LanChang
  # 版本
  version: 3.8.6
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/lancheng/uploadPath
  # profile: /home/projects/treeHole
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  mvc:
    servlet:
      load-on-startup: 1
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 106.53.97.225
    # host: 10.0.12.4
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: Lancheng1688@redis
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# RocketMQ 相关配置
rocketmq:
  # 指定 nameServer
  name-server: 106.53.97.225:9876
  # name-server: 10.0.12.4:9876
  # Producer 生产者
  producer:
    # 指定发送者组名
    group: yingde-tree-group
    # 发送消息超时时间，单位：毫秒。默认为 3000 。
    send-message-timeout: 3000
    # 消息压缩阀值，当消息体的大小超过该阀值后，进行消息压缩。默认为 4 * 1024B
    compress-message-body-threshold: 4096
    # 消息体的最大允许大小。。默认为 4 * 1024 * 1024B
    max-message-size: 4194304
    # 同步发送消息时，失败重试次数。默认为 2 次。
    retry-times-when-send-failed: 2
    # 异步发送消息时，失败重试次数。默认为 2 次。
    retry-times-when-send-async-failed: 2
    # 发送消息给 Broker 时，如果发送失败，是否重试另外一台 Broker 。默认为 false
    retry-next-server: false

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 120

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 微信信息
weixin:
  # 微信应用（小程序、app、网页等等）
  application-info:
    # 微信小程序应用
    mini-applet:
      # 微信小程序-appid
      app-id: wxdfee3a598de0fb18
      # 微信小程序-密钥
      app-secret: 2b375a770a0f32dff4af1c2632ca3a23
    # 公众号
    official-account:
      # appid/密钥
      app-id: wxd82ac8dbf68d12fe
      app-secret: 8bfe014fb58aaf599ca1cf1b3ec94157
      token: 1711759551015522304
      encoding-aes-key: 0Q2FWQBHDhJcIcHWkOBfQEdorbdV2g5SMh9FXNuJVSI
  # 微信支付账号信息
  pay-info:
    # 商户号
    mch-id: 1653587833
    # api密钥
    mch-key: lllwyingdeshichezhidaoqichemaoyi
    # apiv3密钥
    mch-key-v3: JeqJoVbE7QjJ5P3d6QWNzXqKfMMdlbhR
    # 加密方式
    sign-type: MD5
    # 商户证书文件路径
    key-path: classpath:cert/apiclient_cert.p12
    # 商户key证书路径
    app-key-path: classpath:cert/apiclient_key.pem
    # 商户cert证书路径
    app-cert-path: classpath:cert/apiclient_cert.pem
#    notify-url: http://lamlin.natapp1.cc/api/wxCallback/payCallback
#    refund-notify-url: http://lamlin.natapp1.cc/api/wxCallback/refundCallback
    notify-url: https://listen.vipwei.cn/prod-api/api/wxCallback/payCallback
    refund-notify-url: https://listen.vipwei.cn/prod-api/api/wxCallback/refundCallBack

# 腾讯云产品信息
tencent-info:
  secret-id: AKIDztaJrEQQDSdbLsDKFwRkoeGiwvMYYLuF
  secret-key: CCyVwDJDtNdimhQxJTQCnAO3YryvmSu7
  # oss
  oss:
    region: ap-guangzhou
    bucket-name: tree-hole-1320838256
    base-url: https://tree-hole-1320838256.cos.ap-guangzhou.myqcloud.com
    thread_pool: 32

