# 内网 api 服务相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.6.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid-dev
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 30

# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 短信配置
hysms:
  domain: http://47.97.21.146:9090/
  mchId: sms1095d5e5da02f61a
  apiKey: fc62c9800708778b0811419f14ea232c
  notifyUrl:

rsa:
  encrypt:
    open: true # 是否开启加密 true  or  false
    showLog: true # 是否打印加解密log true  or  false
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgJgSr/EwPdvXeO+zzDVUeYQQoNhCWImeHeTXI16TnMJ1CQ3iORsv2dTZ3H2h0szCI0qNKSCcE2IttFRu9bDmaZtYpITpo4sO1YSNUc8LRohd2PJTH68LOpUCRrXnXzEVUJ85+77oDHOnz/IM0lSAbRynufH3NMtdq4mRyNFSavM2nkPghYv0rraWGvvAO+1z+LZmfYuQZ4/BraUp8SnV0S1aJW8f7slJPZdg1nbjIydKxnwezoFzm9wm4cBALxpvlqxdpzNueYbY5xHId5gkw8EfL9EZEStMK6OADXGvVsjQpEg5gnbw9FN4uOfzbRtJm8CwjpfQcRicd5kjwfFB5QIDAQAB # RSA公钥
    privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCAmBKv8TA929d477PMNVR5hBCg2EJYiZ4d5NcjXpOcwnUJDeI5Gy/Z1NncfaHSzMIjSo0pIJwTYi20VG71sOZpm1ikhOmjiw7VhI1RzwtGiF3Y8lMfrws6lQJGtedfMRVQnzn7vugMc6fP8gzSVIBtHKe58fc0y12riZHI0VJq8zaeQ+CFi/SutpYa+8A77XP4tmZ9i5Bnj8GtpSnxKdXRLVolbx/uyUk9l2DWduMjJ0rGfB7OgXOb3CbhwEAvGm+WrF2nM255htjnEch3mCTDwR8v0RkRK0wro4ANca9WyNCkSDmCdvD0U3i45/NtG0mbwLCOl9BxGJx3mSPB8UHlAgMBAAECggEAffR2WV8koXJz20DuG1chJuT0ZJduZMpm1WEQWNSKQUE24Wd37fdzJyoVOqLTnmZwwaCEI4SNW28O1VLeXEipZ0eBy6NkNYw/O2RaB4eEw9FOGvE/+gi6Nuc9E4WY2uR4vD85zBtxrsCZ3lR3uoyKPlWS887NFCkd1qco5EojMB0h0qpj2wF3jcHvfiX8F9s6pd1ZSbHzZMlYD2s1kijcnK8/1zY0l1A4m8f+4/nO65SC8EZO0kMxN2TC86mjy25lMfJlYri1Ol1+1ir7UGBepfS+OBFYVTnUu/cRwpyu94lQ8THSSFIsXjQxIv+P2vuyyGMs5RqDopcXkj44xviBAQKBgQDUOqpf4ZnhozEeJEmOQfe4sll6679RRjfcRdiTi/iv0j2PLj/Z5NzsBINTfeOhKC/FnxYP+qIaYgniXSbLDKC9xO/dCZVhLvoJSAWIZozT32A7VdISfTKkppOQH8y0xPyhvmwfa0gQL0kzrRx7X0jhoFqCreG1ruDZCLPCFAgDjwKBgQCbHZ3hGPMFdPWHBatTrQqWQvMAV9CY4c2SWwZAIvcGEcbXcj9OaFc+a1tpT2p49js6GI7mJbsXZaJOX+xQrgQXyLWEnX9UCuwKX9aU0qgY+Hbzf1NxXgtf1vIFI1BMa0m5gxK1S98I513s5dNvA9JZ7YdnBGojMWS1Ov8dxCzZSwKBgE8M5wc9xg6otZPvmkJVygrOy8ugYivIxufSUGBtA52h5vIdHQVxXOTArZX8zzvo9xpaLmKXTagcGmhpoBiDxJ/K6jlf53dCgznPzNfIsu38RyDyz4O5hJKVxWMqpRo0QZGRlz6AvF/i7RZFhdViYYhBLVV9pRQCZpgQyLwir/V7AoGAOGA0QFp8APC4R+GUmi3bGi+s9+PyqY3v1BCHHgpXM3qEhUs9nPapNsN4DrdRYDNF5WCFlzoBXIiQy+FrFwuX6zkEV/WSEG6DyWV5rM8/TwwG14rgPeTLR4LspVdnWM7plaYAx6mSnz7P0UjaZo/CBPMichuVo8LQ8llF3YCuOC8CgYEApCS3ACebNPTKCa1W4U5csDzBlCYr+IBicopgNCRkhE+ZjkVn8G9XYZKJZrSK0MIaHjqSbzmli7+hN8RaTbXlt9tzGHziu62kEXcXGrmrKHY4GOV8ruVileaKxK8QGWj2dSIU7bHx1g6f4r1tXsnNNCK9R0E4ihjjfFvSwRwcROc= # RSA私钥




